### ISSUE TITLE
 Test Fail: account test › Increase time to specific time point › should increase time to able to add new epoch

### ISSUE THREAD

**Issue by rdewilder** [GenerEOS/Qtest#35]
FAIL  test/passingtime.test.ts (36.271 s)
  ● account test › Increase time to specific time point › should increase time to able to add new epoch

    assertion failure with message: only start next epoch once the previous epoch has done

      at new RpcError (node_modules/eosjs/src/eosjs-rpcerror.ts:14:13)
      at JsonRpc.<anonymous> (node_modules/eosjs/src/eosjs-jsonrpc.ts:97:19)
      at step (node_modules/eosjs/dist/eosjs-jsonrpc.js:37:23)
      at Object.next (node_modules/eosjs/dist/eosjs-jsonrpc.js:18:53)
      at fulfilled (node_modules/eosjs/dist/eosjs-jsonrpc.js:9:58)

**Comment by quocle108** [comment]
@rdewilder which system are you're run the test? FYI, it works fine in MAC M1 ARM64 and Ubuntu AMD64 on my side
